package team2.uco.edu;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author dstr3
 */

public class support_GUI extends javax.swing.JFrame
	{
		/** Creates new form support_GUI */
	public support_GUI()
			{
			    initComponents();
			}
			/** This method is called from within the constructor to
			 * initialize the form.
			 * WARNING: Do NOT modify this code. The content of this method is
			 * always regenerated by the Form Editor.
			 */
			@SuppressWarnings("unchecked")
			    // <editor-fold defaultstate="collapsed" desc="Generated Code">                         
    private void initComponents()
		{
		        jPanel_Patient_Info = new javax.swing.JPanel();
		        jLabel_Patient_Id = new javax.swing.JLabel();
		        jLabel_Age = new javax.swing.JLabel();
		        jLabel_Menopause = new javax.swing.JLabel();
		        jLabel_Tumor_Size = new javax.swing.JLabel();
		        jLabel_Inv_Nodes = new javax.swing.JLabel();
		        jLabel_Node_Caps = new javax.swing.JLabel();
		        jLabel_Deg_Malig = new javax.swing.JLabel();
		        jLabel_Breast = new javax.swing.JLabel();
		        jLabel_Breast_Quad = new javax.swing.JLabel();
		        jLabel_irradiat = new javax.swing.JLabel();
		        
		        jTextField_Patient_Id = new javax.swing.JTextField();
		        jTextField_Age = new javax.swing.JTextField();
		        jTextField_Menopause = new javax.swing.JTextField();
		        jTextField_Tumor_Size = new javax.swing.JTextField();
		        jTextField_Inv_Nodes =new javax.swing.JTextField();
		        jTextField_Node_Caps = new javax.swing.JTextField();
		        jTextField_Deg_Malig = new javax.swing.JTextField();
		        jTextField_Breast = new javax.swing.JTextField();
		        jTextField_Breast_Quad = new javax.swing.JTextField();
		        jTextField_Irradiat = new javax.swing.JTextField();
		        
		        jScrollPane_Sys_Response = new javax.swing.JScrollPane();
		        jTextArea_Sys_Response = new javax.swing.JTextArea();
		        		        
		        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		        jPanel_Patient_Info.setBorder(javax.swing.BorderFactory.createTitledBorder("Patient Info"));
		        
		        // Assigning what to display in variable label
		        jLabel_Patient_Id.setText("Patient Id#");
		        jLabel_Age.setText("Age");
		        jLabel_Menopause.setText("Menopause");
		        jLabel_Tumor_Size.setText("Tumor Size");
		        jLabel_Inv_Nodes.setText("Inv Nodes");
		        jLabel_Deg_Malig.setText("Deg Malig");
		        jLabel_Breast.setText("Breast");
		        jLabel_Breast_Quad.setText("Breast Quad");
		        jLabel_irradiat.setText("Irradiat");
		        jLabel_Node_Caps.setText("Node Caps");
		 
		        javax.swing.GroupLayout jPanel_Patient_InfoLayout = new javax.swing.GroupLayout(jPanel_Patient_Info);
		        jPanel_Patient_Info.setLayout(jPanel_Patient_InfoLayout);
		        jPanel_Patient_InfoLayout.setHorizontalGroup(
		            jPanel_Patient_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		            .addGroup(jPanel_Patient_InfoLayout.createSequentialGroup()
		                .addGroup(jPanel_Patient_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
		                    .addGroup(jPanel_Patient_InfoLayout.createSequentialGroup()
		                        .addGroup(jPanel_Patient_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
		                            .addComponent(jLabel_Tumor_Size, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
		                            .addComponent(jLabel_Menopause, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		                            .addComponent(jLabel_Age, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		                            .addComponent(jLabel_Patient_Id, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
		                        .addGroup(jPanel_Patient_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
		                            .addComponent(jTextField_Patient_Id, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
		                            .addComponent(jTextField_Menopause, 0, 1, Short.MAX_VALUE)
		                            .addComponent(jTextField_Age, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		                            .addComponent(jTextField_Tumor_Size, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
		                    .addGroup(jPanel_Patient_InfoLayout.createSequentialGroup()
		                        .addComponent(jLabel_Breast, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
		                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
		                        .addComponent(jTextField_Breast, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		                    .addGroup(jPanel_Patient_InfoLayout.createSequentialGroup()
		                        .addComponent(jLabel_irradiat, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
		                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
		                        .addComponent(jTextField_Irradiat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		                    .addGroup(jPanel_Patient_InfoLayout.createSequentialGroup()
		                        .addComponent(jLabel_Deg_Malig, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
		                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
		                        .addComponent(jTextField_Deg_Malig, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		                    .addGroup(jPanel_Patient_InfoLayout.createSequentialGroup()
		                        .addComponent(jLabel_Breast_Quad, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
		                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
		                        .addComponent(jTextField_Breast_Quad, 0, 1, Short.MAX_VALUE))
		                    .addGroup(jPanel_Patient_InfoLayout.createSequentialGroup()
		                        .addGroup(jPanel_Patient_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		                            .addComponent(jLabel_Inv_Nodes, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
		                            .addComponent(jLabel_Node_Caps, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
		                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
		                        .addGroup(jPanel_Patient_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		                            .addComponent(jTextField_Inv_Nodes, 0, 55, Short.MAX_VALUE)
		                            .addComponent(jTextField_Node_Caps, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
		                .addGap(0, 19, Short.MAX_VALUE))
		        );
		        jPanel_Patient_InfoLayout.setVerticalGroup(
		            jPanel_Patient_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		            .addGroup(jPanel_Patient_InfoLayout.createSequentialGroup()
		                .addContainerGap()
		                .addGroup(jPanel_Patient_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
		                    .addComponent(jLabel_Patient_Id)
		                    .addComponent(jTextField_Patient_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
		                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		                .addGroup(jPanel_Patient_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
		                    .addComponent(jLabel_Age)
		                    .addComponent(jTextField_Age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
		                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		                .addGroup(jPanel_Patient_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
		                    .addComponent(jLabel_Menopause)
		                    .addComponent(jTextField_Menopause, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
		                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		                .addGroup(jPanel_Patient_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
		                    .addComponent(jLabel_Tumor_Size)
		                    .addComponent(jTextField_Tumor_Size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
		                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		                .addGroup(jPanel_Patient_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
		                    .addComponent(jLabel_Inv_Nodes)
		                    .addComponent(jTextField_Inv_Nodes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
		                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		                .addGroup(jPanel_Patient_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
		                    .addComponent(jLabel_Node_Caps)
		                    .addComponent(jTextField_Node_Caps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
		                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		                .addGroup(jPanel_Patient_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
		                    .addComponent(jLabel_Deg_Malig)
		                    .addComponent(jTextField_Deg_Malig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
		                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		                .addGroup(jPanel_Patient_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
		                    .addComponent(jLabel_Breast)
		                    .addComponent(jTextField_Breast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
		                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		                .addGroup(jPanel_Patient_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
		                    .addComponent(jLabel_Breast_Quad)
		                    .addComponent(jTextField_Breast_Quad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
		                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		                .addGroup(jPanel_Patient_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
		                    .addComponent(jLabel_irradiat)
		                    .addComponent(jTextField_Irradiat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
		                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		        );
		        
		        
		        jScrollPane_Sys_Response.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
		        jTextArea_Sys_Response.setColumns(25);
		        jTextArea_Sys_Response.setRows(15);
		        jScrollPane_Sys_Response.setViewportView(jTextArea_Sys_Response);
		     
		        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		        getContentPane().setLayout(layout);
		        
		        layout.setHorizontalGroup(
		            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		            .addGroup(layout.createSequentialGroup()
		                .addContainerGap()
		                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		                    .addGroup(layout.createSequentialGroup()
		                        .addComponent(jPanel_Patient_Info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
		                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		                        .addComponent(jScrollPane_Sys_Response, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE))
		                    .addGroup(layout.createSequentialGroup()
		                     //   .addComponent(jButton_Request)
		                
		                        .addGap(0, 0, Short.MAX_VALUE)))
		                
		                	//	.addComponent(jButton_Give)
		                .addContainerGap())
		        );
		        
		        layout.setVerticalGroup(
		            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		            .addGroup(layout.createSequentialGroup()
		                .addContainerGap()
		                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
		                    .addComponent(jScrollPane_Sys_Response)
		                    .addComponent(jPanel_Patient_Info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
		             //   .addComponent(jButton_Request)
		             //   .addComponent(jButton_Give)
		                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		        );
		        pack();
			}// </editor-fold>   

    public static void main(String args[])
    		{
				    /* Set the Nimbus look and feel */
				    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
				    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
				         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
				     */
				    try
				    {
				 for(javax.swing.UIManager.LookAndFeelInfo info:javax.swing.UIManager.getInstalledLookAndFeels())
				 {
				     if("Nimbus".equals(info.getName()))
				     {
				  javax.swing.UIManager.setLookAndFeel(info.getClassName());
				  break;
				     }
				 }
				    }catch(ClassNotFoundException ex)
				    {
				 java.util.logging.Logger.getLogger(startup_GUI.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
				    }catch(InstantiationException ex)
				    {
				 java.util.logging.Logger.getLogger(startup_GUI.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
				    }catch(IllegalAccessException ex)
				    {
				 java.util.logging.Logger.getLogger(startup_GUI.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
				    }catch(javax.swing.UnsupportedLookAndFeelException ex)
				    {
				 java.util.logging.Logger.getLogger(startup_GUI.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
				    }
				    //</editor-fold>
				    /* Create and display the form */
				    java.awt.EventQueue.invokeLater(new Runnable()
				    {
				public void run() {
				 new support_GUI().setVisible(true);
				    }
				    });
    			}


				    // Variables declaration - do not modify                    
				    public javax.swing.JButton jButton_Request;
				    public javax.swing.JButton jButton_Give;
				    public javax.swing.JTextField jTextField_Age;
				    public javax.swing.JTextField jTextField_Menopause;
				    public javax.swing.JTextField jTextField_Breast;
				    public javax.swing.JTextField jTextField_Breast_Quad;
				    public javax.swing.JTextField jTextField_Deg_Malig;
				    public javax.swing.JTextField jTextField_Inv_Nodes;
				    public javax.swing.JTextField jTextField_Irradiat;
				    public javax.swing.JTextField jTextField_Node_Caps;
				    public javax.swing.JTextField jTextField_Tumor_Size;
				    
				    private javax.swing.JLabel jLabel_irradiat;
				    private javax.swing.JLabel jLabel_Age;
				    private javax.swing.JLabel jLabel_Breast;
				    private javax.swing.JLabel jLabel_Breast_Quad;
				    private javax.swing.JLabel jLabel_Deg_Malig;
				    private javax.swing.JLabel jLabel_Inv_Nodes;
				    private javax.swing.JLabel jLabel_Menopause;
				    private javax.swing.JLabel jLabel_Node_Caps;
				    private javax.swing.JLabel jLabel_Patient_Id;
				    private javax.swing.JLabel jLabel_Tumor_Size;
				    private javax.swing.JPanel jPanel_Patient_Info;
				    public javax.swing.JScrollPane jScrollPane_Sys_Response;
				    public javax.swing.JTextArea jTextArea_Sys_Response;
				    public javax.swing.JTextField jTextField_Patient_Id;
				    public boolean request_clicked = false;
				    public boolean give_clicked = false;
				    // End of variables declaration                  
	}

